CREATE TABLE IF NOT EXISTS cities (id UUID PRIMARY KEY, "name" VARCHAR(255) NOT NULL, population INT NOT NULL);
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, "name" VARCHAR(50) NOT NULL, age INT NOT NULL);
