ALTER TABLE cars ADD COLUMN address_line1 VARCHAR(255);
ALTER TABLE cars ADD COLUMN address_line2 VARCHAR(255);
ALTER TABLE cars ADD COLUMN postal_code VARCHAR(32);
ALTER TABLE cars ADD COLUMN city VARCHAR(120);
ALTER TABLE cars ADD COLUMN country VARCHAR(120);
ALTER TABLE cars ADD COLUMN formatted_address VARCHAR(255);
